version: "3"
services:
  serveur-dev:
    build: .
    container_name: serveur-dev
    ports:
      - "2222:22"
  serveur-prod:
    build: .
    container_name: serveur-prod
    ports:
      - "2200:22"
